# Generated by Django 4.2.4 on 2023-09-01 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refview', '0003_imagepost_preview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagepost',
            name='preview',
        ),
    ]
